name: Weekly dependency update

on:
  schedule:
    - cron: "0 23 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  taze-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          run_install: false

      - name: Use Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Verify pnpm
        run: pnpm --version

      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Update dependencies with taze (workspaces)
        run: pnpm dlx taze@latest -w

      - name: Refresh lockfile (pnpm)
        run: pnpm install --lockfile-only

      - name: Build
        run: pnpm -r build

      - name: Check for changes
        id: changes
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add -A
          if git diff --cached --quiet; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "No changes detected"
          else
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "Changes detected"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: deps/weekly-update-${{ github.run_number }}
          base: master
          delete-branch: true
          title: "chore(deps): weekly update via taze (pnpm)"
          body: |
            Automated weekly dependency update using `taze -w` with pnpm.
            
            This PR was automatically created by the weekly dependency update workflow.
          commit-message: "chore(deps): weekly update via taze (pnpm)"